// unit-role: edge — tests the pure generateReadme function for all boundary inputs:
// empty progress, multiple solved exercises (sorted), zero XP and zero streak. No mocks.
import { describe, it, expect } from 'bun:test';
import { generateReadme } from '../src/github-sync.js';

describe('generateReadme', () => {
  it('produces title and footer with no exercises', () => {
    const md = generateReadme({ completedExercises: {} });
    expect(md).toContain('# The Refactory — My Solutions');
    expect(md).toContain('*Auto-generated by [The Refactory]');
    expect(md).not.toContain('## Completed Exercises');
  });

  it('includes summary line with correct values', () => {
    const progress = {
      xp: 42,
      streak: 3,
      completedExercises: {
        'two-sum': { solvedAt: '2024-01-01' },
        'fizzbuzz': { solvedAt: '2024-01-02' },
      },
    };
    const md = generateReadme(progress);
    expect(md).toContain('Solved: **2**');
    expect(md).toContain('XP: **42**');
    expect(md).toContain('Streak: **3**');
  });

  it('lists solved exercises sorted alphabetically', () => {
    const progress = {
      xp: 10,
      streak: 1,
      completedExercises: {
        'two-sum': { solvedAt: '2024-01-01' },
        'fizzbuzz': { solvedAt: '2024-01-02' },
        'add-two': { solvedAt: '2024-01-03' },
      },
    };
    const md = generateReadme(progress);
    expect(md).toContain('## Completed Exercises');
    const addIdx = md.indexOf('add-two');
    const fizzIdx = md.indexOf('fizzbuzz');
    const twoIdx = md.indexOf('two-sum');
    expect(addIdx).toBeLessThan(fizzIdx);
    expect(fizzIdx).toBeLessThan(twoIdx);
  });

  it('formats each exercise as a backtick list item', () => {
    const progress = {
      xp: 5,
      streak: 0,
      completedExercises: { 'hello-world': { solvedAt: '2024-01-01' } },
    };
    const md = generateReadme(progress);
    expect(md).toContain('- `hello-world`');
  });

  it('handles zero XP and zero streak', () => {
    const progress = { xp: 0, streak: 0, completedExercises: {} };
    const md = generateReadme(progress);
    expect(md).toContain('XP: **0**');
    expect(md).toContain('Streak: **0**');
    expect(md).toContain('Solved: **0**');
  });

  it('handles missing xp/streak/completedExercises gracefully', () => {
    const md = generateReadme({});
    expect(md).toContain('XP: **0**');
    expect(md).toContain('Streak: **0**');
    expect(md).toContain('Solved: **0**');
    expect(md).not.toContain('## Completed Exercises');
  });
});
